docker: &docker
  machine:
    enabled: true
    image: circleci/classic:201709-01


version: 2.1
jobs:
  build:
    <<: *docker
    steps:
      - checkout
      - run: docker version
      - run: docker-compose --version
      - run: docker build .
